### ISSUE TITLE
Infinite vibration bug since version 2.0.11

### ISSUE THREAD

**Issue by Robyer** [Ryochan7/DS4Windows#1147]
After update DS4Windows to 2.0.11 or 2.0.12 versions I started experiencing weird bug in the Last Year game (I'm not sure if it affects other games, but here it's always reproducible for me.

When some action in game triggers vibration in controller (I use DS4v2 with official Sony Wireless Adaptor, in exclusive mode) then the controller keeps vibrating at some low intensity indefinitely. When I turn off controller and turn it on again it works again without vibration until game starts sends some vibration event again.

When I downgrade to the 2.0.10 version it works correctly without this issue.

**Comment by Ryochan7** [comment]
Are you emulating a virtual DS4?

**Comment by Robyer** [comment]
@Ryochan7 Yes, that is correct. I don't know if the bug is present when emulating XBOX Controller. Should I try it?

**Comment by Ryochan7** [comment]
I recently made a change to the DS4 Feedback routine to take lightbar color updates into account. That is needed for the Passthru lightbar routine to work as intended for PC games that can use the lightbar (Witcher 3). The routine change was fairly simple and I would have thought that the rumble case would have been covered. I will have to run some tests.

I would assume that force feedback through an emulated Xbox 360 controller would still work as intended.

**Comment by Robyer** [comment]
I confirm that bug is not present when emulating Xbox 360 controller.

**Comment by Yohoki** [comment]
Just saw the Changelog, and figured I'd add another game to the list. This bug also affects the game "Sayonara Wild Hearts", when using DS4 mode. It is fixed in the newest update, using the old routines.

In old update, it would also work normally until the game makes the controller rumble, and then it would continue to rumble indefinitely.

**Comment by BitGrub** [comment]
Witcher 3 and Sayonara Wild hearts work perfectly for me, no infinite rumble after playing through a couple hours of The Witcher and all the way through Sayonara Wild hearts. 

I have a DS4v2 in DS4 mode (passthru enabled and working), DS4Windows version 2.0.13 (the last version with passthru support)

**Comment by Robyer** [comment]
I must say that this bug is back in version 2.1.4. So that DS4 feedback routine is still broken somehow.
