### ISSUE TITLE
Rocket League works without using DS4Windows but doesn't work when using it

### ISSUE THREAD

**Issue by sondr3** [Ryochan7/DS4Windows#27]
I'm having a strange issue where using your version of DS4Windows makes Rocket League not recognize the controller. When I stop DS4Windows the DS4 immediately starts working in RL but when I turn it on it stops. The controller is obviously working because using the touchpad as a mouse works fine, it's just the input from the controller that RL somehow doesn't get.

**Comment by Ryochan7** [comment]
I believe that Rocket League has native support for the DS4 so there isn't really a need to use DS4Windows for that game. I don't have the game so I can't test why it would have problems recognizing the emulated Xbox 360 controller.

**Comment by sondr3** [comment]
Yeah, I know that, I just like it because I have bound some button combinations for media playback while playing games which is a bit annoying losing. Not sure what gives either, it worked a week ago.

**Comment by diogocalgaro** [comment]
Hi, for me it is the opposite. I have Rocket League and the DS4 works badly or doesn't work at all in the game. But when I use DS4Windows it works flawlessly. I can make some tests, if would help any of you.
I am using the Sony dongle.

**Comment by Ryochan7** [comment]
Good thing for the free weekend event. Under normal circumstances, Rocket League works on my system in native DS4 mode and emulated Xbox 360 mode. However, I am assuming that you ran into the Exclusive Mode bug that was fixed recently. Testing with the current stable release caused my DS4 to become unresponsive and required rebooting Windows to correct the problem. I have occasionally run into that problem since I started using DS4Windows back around November.

One way around that problem with the current stable release (1.4.67) is to always run DS4Windows as the Administrator. A new version with the Exclusive Mode bug fixed should be released on Friday.

**Comment by sondr3** [comment]
I just tried the newest release and the problem is still there, my touchpad still works fine as a mouse but none of the sticks or buttons are responsive in RL while using DS4Windows. Not really sure what gives :(

**Comment by sondr3** [comment]
It's actually in general, I just tried in Duck Game and TrackMania and in none of the games did the controller respond to anything while using DS4Windows while not using it they work fine. The touchpad on the controller still responds as a mouse while this is happening so I can select menu items and such with the touchpad but nothing with the actual physical buttons is happening.

**Comment by Ryochan7** [comment]
DS4Windows can apparently read input reports fine but the controller state is not converted to the corresponding XInput report. I would assume that you can see output in the Controller Readings tab. Can you share the profile that you are trying to use? Maybe some mapping is not working properly or maybe something is wrong with the connection to the Scp Virtual Bus Driver.

**Comment by sondr3** [comment]
Yeah, the input is working fine in DS4Windows, I can see all the readings and button presses as well so I'm not really sure what gives. This is my profile: https://pastebin.com/AEuZRFAB.

**Comment by Ryochan7** [comment]
I had to create the actions but the profile works on my system. I am not sure what the problem is. You said it worked fine until about a week ago. Does an older version of DS4Windows work on your system? Unless something is wrong with the Scp Virtual Bus Driver then I am at a loss. You can try re-installing it but I am not too sure that it would help you.

http://23.239.26.40/ds4windows/files/Virtual%20Bus%20Driver.zip

**Comment by sondr3** [comment]
I tried with older versions of DS4Windows, even went back to the original version to make sure I wasn't going crazy. I really have no idea myself either, I'll try to reinstall some drivers and whatnot and see if something pops up.

**Comment by sondr3** [comment]
No idea what happened but I downloaded the latest version and it works fine now. ¯\\\_(ツ)_/¯
