### ISSUE TITLE
DS4Windows Crashed After Saving Shift Modifiers

### ISSUE THREAD

**Issue by Perseonn** [Ryochan7/DS4Windows#2769]
**Describe the bug**
DS4Windows crashes after some delay when saving profile that has a Shift Modifier on active controller. Present on both existing and new profile. Observed in 3.2.1 and 3.2.2

**To Reproduce**
1. Connect controller via Bluetooth
2. Activate an X-box emulated profile on a controller 
3. Click Edit Profile
4. Click on Share Button
5. Click on Shift Modifier
6. Select L1
7. Click N
8. Save (Profile)
9. DS4 Windows crashed after loading while the controller stays connected to Windows
10. Disconnect Controller
11. Open DS4Windows
12. Reconnecting controller will result in crash since the loaded profile contains the Shift Modifier
13. Disconnect Controller
14. Open DS4Windows
15. Editing the profile to remove any Shift Modifers and reconnecting controller will prevent crash

**Expected behavior**
DS4Windows saves the profile and operates as normal.

**Screenshots and Logs**
[ds4windows_log_20230108.10.txt](https://github.com/Ryochan7/DS4Windows/files/10368269/ds4windows_log_20230108.10.txt)
[ds4windows_log_20230108.11.txt](https://github.com/Ryochan7/DS4Windows/files/10368270/ds4windows_log_20230108.11.txt)
[ds4windows_log_20230108.12.txt](https://github.com/Ryochan7/DS4Windows/files/10368271/ds4windows_log_20230108.12.txt)
[ds4windows_log_20230108.13.txt](https://github.com/Ryochan7/DS4Windows/files/10368272/ds4windows_log_20230108.13.txt)
[ds4windows_log_20230108.14.txt](https://github.com/Ryochan7/DS4Windows/files/10368273/ds4windows_log_20230108.14.txt)
[ds4windows_log_20230108.15.txt](https://github.com/Ryochan7/DS4Windows/files/10368274/ds4windows_log_20230108.15.txt)
[ds4windows_log_20230108.16.txt](https://github.com/Ryochan7/DS4Windows/files/10368275/ds4windows_log_20230108.16.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 (CUH-ZCT2E) Pretty sure not an original controller.
 - OS: Windows 10 Pro 21H2 / OS Build 19044.2364
 - DS4Windows Version 3.2.1 and 3.2.2

**Additional context**
Rolled back to 3.1.12 to circumvent the issue.

**Comment by DigitalMenace242** [comment]
happens to me too. L1 > shift to "T" .
using real dualshock 4 and windows LTSC

**Comment by sonny-dev** [comment]
My issue is similar, but I **can** save modifiers, just **not** when it's a Modifier that uses a **Macro**. 

I'm making the X/A Button have R1/RB as the modifier, and the macro is (V + Space). 

I can save the Macro, but when I save the Controller Profile, DS4windows will crash. 

Have been experiencing this from the last few patches, will downgrade and check.

**Comment by sonny-dev** [comment]
Update: Just tried to set the Shift Modifier of X/A & R1/RB as V. 
Saving caused the Program to crash too.

**Comment by rasenfer** [comment]
Apparently works well now for me on 3.2.6

**Comment by Perseonn** [comment]
Thanks for the reminder! It seems to have fixed in the 3.2.6!

**Comment by sonny-dev** [comment]
Still broken for me in 3.2.7
Crashes after saving a Shift Modifier

**Comment by DigitalMenace242** [comment]
Fucking dork coders close an issue even if it isnt fix because they suck at coding, and life.

**Comment by Ryochan7** [comment]
> Fucking dork coders close an issue even if it isnt fix because they suck at coding, and life.

I did not even close this issue; it was closed by OP @Perseonn. I fixed his problem according to his last post.

You did not include a profile for reference. I cannot solve an unknown problem by clairvoyance. Miserable failure at life.

**Comment by Ryochan7** [comment]
![hey-peter-whats-happening](https://github.com/Ryochan7/DS4Windows/assets/581968/86babea7-7cf0-45cb-b8b4-5e4827fb1728)

**Comment by Ryochan7** [comment]
Looks like @DigitalMenace242 deleted his account. Thank you for reminding me how evil many of you people truly are. People expect a lot out of me but cannot even be friendly while talking to me. You are not my boss and this is not Initech. Go outside for a while.

I double checked the macro saving problem mentioned by sonny-dev and that use case works for me in version 3.2.11.

Locking this thread as the original issue was resolved months ago. No need for someone else to jump in and add on further.
