### ISSUE TITLE
Problem shutting down the PC, DS4 exception error pop up.

### ISSUE THREAD

**Issue by Trihy** [Ryochan7/DS4Windows#2880]
**Describe the bug**
When turning off the PC (Windows 11), nothing happens, stays for a while, and an error windows pop up appears.

It says something about Exception H.NotifyIcon_(many numbers) DS4Windows

**To Reproduce**

Just shutdown the PC

**Expected behavior**
Pc shutting down

**Screenshots and Logs**
Will post a picture of the error if needed

**Desktop (please complete the following information):**

Windows11

Using Dualsense, but none connected when shutting down system. Not sure if when one connected, error will happen.

Also never seen this before 3.2.9, but cant confirm 100%

Tried on a clean Win11 install, but the same.

**Comment by Trihy** [comment]
I noticed the problem occurs mostly when turning off the PC while the monitor is off. Hit the power button and wont turn off. Turn on the monitor and the H.notifyicon error is there.

**Comment by Ryochan7** [comment]
Maybe this issue has been fixed with recent changes. Had H.NotifyIcon error out while playing with Suspend / Resume changes lately. Been busy with AFK stuff lately.

**Comment by Trihy** [comment]
Yes, saw some changes in code about suspend. I think is related. Will try new build and report back.

**Comment by Luna-Nocturna** [comment]
I still encounter this issue every other day. Even with the latest build. In my case not related to the monitor however.

Additional: My Windows (10) shutdown is set to a full shutdown. Have to because otherwise Wake-on-Wan doesn't work.

**Comment by Ryochan7** [comment]
The original issue has been fixed and no new relevant information has been posted. People don't want to help solve their supposed problems; the logs show shutting down works for me. Likely just gaslighting anyway.
