### ISSUE TITLE
DS4 wont start with windows anymore

### ISSUE THREAD

**Issue by cristianmars** [Ryochan7/DS4Windows#513]
hello im posting to notify that ds4 windows wont start on start up any more , it stopped working propperly a long time ago, yes its enabled on the start up menu on windows 10 , tried a lot of thing none of them worked , the other programs are working properly , i wanted to know if this have a solution or in any case just notify the problem.

**Comment by Ryochan7** [comment]
The Task option initially broke with version 1.5.15 because of permission request changes. The issue was resolved with version 1.5.16. Firstly, I would suggest that you disable and re-enable the Run at Startup option in DS4Windows to create new entries for startup. Other than that, you might need to run `shell:startup` to see how the shortcut was written and the Windows Task Scheduler to make sure that it can run outside of system startup. Also, you might need to check Task Manager and see if the Startup entry for DS4Windows is currently enabled.

**Comment by Pit1209** [comment]
> 
> 
> The Task option initially broke with version 1.5.15 because of permission request changes. The issue was resolved with version 1.5.16. Firstly, I would suggest that you disable and re-enable the Run at Startup option in DS4Windows to create new entries for startup. Other than that, you might need to run `shell:startup` to see how the shortcut was written and the Windows Task Scheduler to make sure that it can run outside of system startup. Also, you might need to check Task Manager and see if the Startup entry for DS4Windows is currently enabled.

I've done everything on that reply but the program is still not loading on start up. It is even showing in task manager and I created new a task on task scheduler with no avail.

**Comment by powerpuffboysz** [comment]
I can second that ds4windows won't start with windows

**Comment by powerpuffboysz** [comment]
if any of you are running ds4windows in admin mode from compatibility settings, uncheck that box and then windows startup functionality should work

**Comment by Ryochan7** [comment]
That is the case due to Windows security features. If you want to run DS4Windows at startup with admin privileges then the Task option has to be used.

**Comment by Pit1209** [comment]
> 
> 
> if any of you are running ds4windows in admin mode from compatibility settings, uncheck that box and then windows startup functionality should work

Many thanks, now it is resolved.
